"""串阳首阴扫描阈值。"""

STRING_YANG_MIN_COUNT = 5
MAX_YANG_PCT = 7.0
PRICE_MA_LOOKBACK_BARS = 60
MAX_PRICE_MA_RATIO = 1.08
RECENT_LIMIT_LOOKBACK_DAYS = 20
DEFAULT_TOP_K_SECTORS = 5
DEFAULT_TOP_CONCEPTS = 8
CONCEPT_PREFETCH_MIN = 40
CONCEPT_PREFETCH_MULTIPLIER = 5
TEACHER_LOOKBACK_DAYS = 7
# 老师观点喂给 LLM 的条数/单段截断上限。2026-07-11 校准：原 20 条×180 字 ≈10KB+ payload
# 是三处 LLM 调用里最大的（board-break 双卡、daily-leaders 均远小于此），与其连续多日
# 降级而兄弟任务正常的分化现象相关；瘦身到 8×120 保留近几日核心观点、砍掉长尾。
TEACHER_NOTES_LIMIT = 8
TEACHER_SNIPPET_CHARS = 120
RANGE_LOOKBACK_DAYS = 140
LIMIT_DETECT_FACTOR = 0.98
CONCEPT_MAX_MEMBERS = 300

REPORT_DIR = "data/reports/string-yang"
