"""串阳首阴扫描阈值。"""

STRING_YANG_MIN_COUNT = 5
MAX_YANG_PCT = 7.0
PRICE_MA_LOOKBACK_BARS = 60
MAX_PRICE_MA_RATIO = 1.08
RECENT_LIMIT_LOOKBACK_DAYS = 20
DEFAULT_TOP_K_SECTORS = 5
DEFAULT_TOP_CONCEPTS = 8
TEACHER_LOOKBACK_DAYS = 7
RANGE_LOOKBACK_DAYS = 140
LIMIT_DETECT_FACTOR = 0.98
CONCEPT_MAX_MEMBERS = 300

REPORT_DIR = "data/reports/string-yang"
