"""接口注册表：定义原始事实层的接口元数据。"""
from __future__ import annotations

from typing import TypedDict


class InterfaceConfig(TypedDict, total=False):
    interface_name: str
    provider_method: str
    stage: str
    use_cases: list[str]
    params_policy: str
    dedupe_keys: list[str]
    raw_table: str
    enabled_by_default: bool
    notes: str


INTERFACE_REGISTRY: dict[str, InterfaceConfig] = {
    "stock_basic": {
        "interface_name": "stock_basic",
        "provider_method": "get_stock_basic_list",
        "stage": "backfill",
        "use_cases": ["history_compare", "research"],
        "params_policy": "metadata_refresh",
        "dedupe_keys": [],
        "raw_table": "raw_stock_basic",
        "enabled_by_default": False,
        "notes": "A股主数据底表，供参数展开与本地映射使用。",
    },
    "trade_cal": {
        "interface_name": "trade_cal",
        "provider_method": "get_trade_calendar",
        "stage": "backfill",
        "use_cases": ["history_compare", "research"],
        "params_policy": "metadata_refresh",
        "dedupe_keys": [],
        "raw_table": "raw_trade_cal",
        "enabled_by_default": False,
        "notes": "交易日历底表，供日/周/月窗口和回填任务复用。",
    },
    "ths_index": {
        "interface_name": "ths_index",
        "provider_method": "get_ths_index",
        "stage": "backfill",
        "use_cases": ["research", "history_compare"],
        "params_policy": "metadata_refresh",
        "dedupe_keys": [],
        "raw_table": "raw_ths_index",
        "enabled_by_default": False,
        "notes": "同花顺板块主数据，补题材板块编码体系。",
    },
    "ths_member": {
        "interface_name": "ths_member",
        "provider_method": "get_ths_member",
        "stage": "backfill",
        "use_cases": ["research", "history_compare"],
        "params_policy": "metadata_refresh",
        "dedupe_keys": [],
        "raw_table": "raw_ths_member",
        "enabled_by_default": False,
        "notes": "同花顺板块成分，供板块内龙头/前排/跟风归属。",
    },
    "index_classify": {
        "interface_name": "index_classify",
        "provider_method": "get_index_classify",
        "stage": "backfill",
        "use_cases": ["research", "history_compare"],
        "params_policy": "metadata_refresh",
        "dedupe_keys": [],
        "raw_table": "raw_index_classify",
        "enabled_by_default": False,
        "notes": "申万行业分类主数据，补行业逻辑板块底座。",
    },
    "daily_basic": {
        "interface_name": "daily_basic",
        "provider_method": "get_daily_basic",
        "stage": "post_core",
        "use_cases": ["post_report", "plan_diagnostics", "history_compare"],
        "params_policy": "trade_date",
        "dedupe_keys": ["ts_code", "trade_date"],
        "raw_table": "raw_daily_basic",
        "enabled_by_default": True,
        "notes": "盘后核心基础面快照，用于日级指标与计划诊断。",
    },
    "adj_factor": {
        "interface_name": "adj_factor",
        "provider_method": "get_adj_factor",
        "stage": "post_core",
        "use_cases": ["post_report", "history_compare"],
        "params_policy": "trade_date",
        "dedupe_keys": ["ts_code", "trade_date"],
        "raw_table": "raw_adj_factor",
        "enabled_by_default": True,
        "notes": "复权因子，供历史走势和后续诊断使用。",
    },
    "moneyflow_hsgt": {
        "interface_name": "moneyflow_hsgt",
        "provider_method": "get_northbound",
        "stage": "post_core",
        "use_cases": ["post_report", "plan_diagnostics"],
        "params_policy": "trade_date",
        "dedupe_keys": ["trade_date"],
        "raw_table": "raw_moneyflow_hsgt",
        "enabled_by_default": True,
        "notes": "北向资金核心数据，属于盘后主流程硬依赖。",
    },
    "daily_info": {
        "interface_name": "daily_info",
        "provider_method": "get_daily_info",
        "stage": "post_core",
        "use_cases": ["post_report", "plan_diagnostics", "history_compare"],
        "params_policy": "trade_date",
        "dedupe_keys": ["trade_date"],
        "raw_table": "raw_daily_info",
        "enabled_by_default": True,
        "notes": "交易所市场交易统计，补大势与成交结构观察。",
    },
    "limit_step": {
        "interface_name": "limit_step",
        "provider_method": "get_limit_step",
        "stage": "post_core",
        "use_cases": ["post_report", "plan_diagnostics", "history_compare"],
        "params_policy": "trade_date",
        "dedupe_keys": ["trade_date"],
        "raw_table": "raw_limit_step",
        "enabled_by_default": True,
        "notes": "连板天梯，直接服务情绪周期与晋级结构判断。",
    },
    "limit_cpt_list": {
        "interface_name": "limit_cpt_list",
        "provider_method": "get_limit_cpt_list",
        "stage": "post_core",
        "use_cases": ["post_report", "plan_diagnostics", "history_compare"],
        "params_policy": "trade_date",
        "dedupe_keys": ["trade_date"],
        "raw_table": "raw_limit_cpt_list",
        "enabled_by_default": True,
        "notes": "最强板块统计，补涨停强度视角的主线判断。",
    },
    "moneyflow_ind_ths": {
        "interface_name": "moneyflow_ind_ths",
        "provider_method": "get_sector_moneyflow_ths",
        "stage": "post_core",
        "use_cases": ["post_report", "plan_diagnostics", "history_compare"],
        "params_policy": "trade_date",
        "dedupe_keys": ["trade_date"],
        "raw_table": "raw_moneyflow_ind_ths",
        "enabled_by_default": True,
        "notes": "同花顺行业资金流向，补板块资金确认。",
    },
    "moneyflow_ind_dc": {
        "interface_name": "moneyflow_ind_dc",
        "provider_method": "get_sector_moneyflow_dc",
        "stage": "post_core",
        "use_cases": ["post_report", "plan_diagnostics", "history_compare"],
        "params_policy": "trade_date",
        "dedupe_keys": ["trade_date"],
        "raw_table": "raw_moneyflow_ind_dc",
        "enabled_by_default": True,
        "notes": "东财行业/概念资金流向，补题材维度资金确认。",
    },
    "moneyflow_mkt_dc": {
        "interface_name": "moneyflow_mkt_dc",
        "provider_method": "get_market_moneyflow_dc",
        "stage": "post_core",
        "use_cases": ["post_report", "plan_diagnostics", "history_compare"],
        "params_policy": "trade_date",
        "dedupe_keys": ["trade_date"],
        "raw_table": "raw_moneyflow_mkt_dc",
        "enabled_by_default": True,
        "notes": "东财大盘资金流向，补大势与增量/存量判断。",
    },
    "margin": {
        "interface_name": "margin",
        "provider_method": "get_margin_data",
        "stage": "post_extended",
        "use_cases": ["post_report", "plan_diagnostics", "research"],
        "params_policy": "trade_date",
        "dedupe_keys": ["trade_date", "exchange_id"],
        "raw_table": "raw_margin",
        "enabled_by_default": True,
        "notes": "融资融券数据，属于扩展事实层，可支持计划诊断。",
    },
    "margin_detail": {
        "interface_name": "margin_detail",
        "provider_method": "get_margin_detail",
        "stage": "post_extended",
        "use_cases": ["post_report", "plan_diagnostics", "research"],
        "params_policy": "trade_date",
        "dedupe_keys": ["trade_date"],
        "raw_table": "raw_margin_detail",
        "enabled_by_default": True,
        "notes": "逐股融资融券明细，补容量核心和趋势中军观察。",
    },
    "block_trade": {
        "interface_name": "block_trade",
        "provider_method": "get_block_trade",
        "stage": "post_extended",
        "use_cases": ["watchlist_context", "research", "history_compare"],
        "params_policy": "trade_date",
        "dedupe_keys": ["ts_code", "trade_date", "price", "vol"],
        "raw_table": "raw_block_trade",
        "enabled_by_default": True,
        "notes": "盘后扩展接口，用于观察机构大宗交易和关注池上下文。",
    },
    "top_inst": {
        "interface_name": "top_inst",
        "provider_method": "get_dragon_tiger",
        "stage": "post_extended",
        "use_cases": ["post_report", "watchlist_context", "research"],
        "params_policy": "trade_date",
        "dedupe_keys": ["ts_code", "trade_date", "exalter"],
        "raw_table": "raw_top_inst",
        "enabled_by_default": True,
        "notes": "龙虎榜机构席位数据，扩展观察，不作为主流程硬依赖。",
    },
    "stock_st": {
        "interface_name": "stock_st",
        "provider_method": "get_stock_st",
        "stage": "post_extended",
        "use_cases": ["post_report", "history_compare", "research"],
        "params_policy": "trade_date",
        "dedupe_keys": ["trade_date"],
        "raw_table": "raw_stock_st",
        "enabled_by_default": True,
        "notes": "ST 列表，供风控与样本清洗使用。",
    },
    "anns_d": {
        "interface_name": "anns_d",
        "provider_method": "get_market_announcements",
        "stage": "post_extended",
        "use_cases": ["watchlist_context", "research", "history_compare"],
        "params_policy": "trade_date",
        "dedupe_keys": ["ann_date"],
        "raw_table": "raw_anns_d",
        "enabled_by_default": True,
        "notes": "全市场公告原始层，补公告回溯和关注池事件筛查。",
    },
    "disclosure_date": {
        "interface_name": "disclosure_date",
        "provider_method": "get_disclosure_dates",
        "stage": "post_extended",
        "use_cases": ["watchlist_context", "research", "history_compare"],
        "params_policy": "quarter_end",
        "dedupe_keys": ["end_date"],
        "raw_table": "raw_disclosure_date",
        "enabled_by_default": True,
        "notes": "财报披露计划，补日历效应与财报季节点观察。",
    },
    "stk_limit": {
        "interface_name": "stk_limit",
        "provider_method": "get_stock_limit_prices",
        "stage": "pre_core",
        "use_cases": ["watchlist_context", "research"],
        "params_policy": "trade_date",
        "dedupe_keys": ["trade_date"],
        "raw_table": "raw_stk_limit",
        "enabled_by_default": False,
        "notes": "当日涨跌停价在 8:40 左右更新，适合盘中前置检查，不纳入 07:00 默认任务。",
    },
    "share_float": {
        "interface_name": "share_float",
        "provider_method": "get_share_float",
        "stage": "backfill",
        "use_cases": ["research", "history_compare"],
        "params_policy": "float_date",
        "dedupe_keys": ["float_date"],
        "raw_table": "raw_share_float",
        "enabled_by_default": False,
        "notes": "解禁数据以历史回填和研究为主，默认不参与每日任务。",
    },
    "regulatory_suspend": {
        "interface_name": "regulatory_suspend",
        "provider_method": "get_suspend_list",
        "stage": "post_extended",
        "use_cases": ["post_report", "research", "history_compare"],
        "params_policy": "trade_date",
        "dedupe_keys": ["trade_date"],
        "raw_table": "raw_regulatory_suspend",
        "enabled_by_default": True,
        "notes": "停复牌（停牌）原始数据，监管核查与停牌标的。",
    },
    "stk_shock": {
        "interface_name": "stk_shock",
        "provider_method": "get_stk_shock",
        "stage": "post_extended",
        "use_cases": ["post_report", "research", "history_compare"],
        "params_policy": "trade_date",
        "dedupe_keys": ["trade_date"],
        "raw_table": "raw_stk_shock",
        "enabled_by_default": True,
        "notes": "交易所公布的个股异常波动（stk_shock，高积分）。",
    },
}


def list_interfaces() -> list[InterfaceConfig]:
    """按 stage 和 interface_name 排序返回注册表。"""
    return sorted(
        INTERFACE_REGISTRY.values(),
        key=lambda item: (item["stage"], item["interface_name"]),
    )


def get_interface(name: str) -> InterfaceConfig | None:
    return INTERFACE_REGISTRY.get(name)
